# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cppBASMastersample <- function() {
    invisible(.Call(`_uc511_cppBASMastersample`))
}

#' Solve system of linear congruence from HIP paper to order HIP boxes.
#' See page 5 of Robertson et al. 2018 Halton Iterative Partitioning.
#' This is essentially an internal function and shouldn't be worried about.
#'
#'
#' @param A Matrix that is in numeric for computational reasons but is the a_i solutions for all HIP boxes.
#' @param base Co-prime Base but generally for BAS work it is 2 or 3.
#' @param J Integer of 2 values that represent the numbers 2^J1, 3^J2.
#'
#'
#' @export
SolveCongruence <- function(A, base, J) {
    .Call(`_uc511_SolveCongruence`, A, base, J)
}

#' Fast Implementation of finding x and y order numbers to feed into the linear congruence equation.
#' This solves equation solves for a_i in the HIP paper.
#' This is essentially an internal function and shouldn't be worried about.
#'
#'
#' @param lxy A Matrix of lower x y coordinates of a Halton Box inside the unit box.
#' @param base Co-prime Base but generally for BAS work it is 2 or 3.
#' @param J Integer of 2 values that represent the numbers 2^J1, 3^J2.
#'
#' @export
GetBoxIndices <- function(lxy, base, J) {
    .Call(`_uc511_GetBoxIndices`, lxy, base, J)
}

#' Draw Halton Sequence values for a single dimension.
#' Note that this was borrowed from the Internet and is not my implementation.
#'
#'
#' @param x An integer for the starting index k >= 0.
#' @param base Co-prime Base but generally for BAS work it is 2 or 3.
#' @param n Number of samples to draw.
#'
#' @examples
#' HaltonSeq(k = 0, base = 2, n = 10)
#'
#' @export
cppHaltonSeq <- function(k, base, n) {
    .Call(`_uc511_cppHaltonSeq`, k, base, n)
}

#'
#' @export
compareBoxesBoxInit <- function(boxes, boxInit, intB) {
    .Call(`_uc511_compareBoxesBoxInit`, boxes, boxInit, intB)
}

#'
#' @export
cppWhere2Start <- function(J, seeds, bases, boxes) {
    .Call(`_uc511_cppWhere2Start`, J, seeds, bases, boxes)
}

#'
#' @export
cppSumPoweredElements <- function(J, bases, numElements) {
    .Call(`_uc511_cppSumPoweredElements`, J, bases, numElements)
}

#'
#' @export
vectorMod <- function(k, b) {
    .Call(`_uc511_vectorMod`, k, b)
}

#'
#' @export
log_a_to_base_b <- function(a, b) {
    .Call(`_uc511_log_a_to_base_b`, a, b)
}

#'
#' @export
cppRSHalton <- function(n, seeds, bases, boxes, J) {
    .Call(`_uc511_cppRSHalton`, n, seeds, bases, boxes, J)
}

